[build]
  publish = "build/"
  command = "yarn build"

  # Develop Branch Deploy context: All deploys that are not in
  # an active Deploy Preview will inherit these settings.
[context.develop]
  [context.develop.environment]
  NODE_VERSION='9.10.0'
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_PROD_ETHEREUM_PROVIDER="https://kovan.infura.io/v3/9c26dd38fd2e44e6bcff6a133eb67930"
  REACT_APP_DEV_ARBITRABLE_TOKEN_LIST_ADDRESS="0xb1323969528dd7cf2e62ff85642c624a8cd5c3fd"
  REACT_APP_DEV_ARBITRABLE_ADDRESS_LIST_ADDRESS="0xcb0216ef49340d63fd22aa16c4ad61658b2875cb"
  REACT_APP_DEV_ARBITRATOR_ADDRESS="0x8847c0947a613c3de443f73351c3815ad0d37f98"
  REACT_APP_DEV_FILE_BASE_URL="https://staging-cfs.s3.us-east-2.amazonaws.com"
  REACT_APP_DEV_FILE_UPLOAD_URL="https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/cfs"
  REACT_APP_DEV_PATCH_USER_SETTINGS_URL="https://8a8aoprv935hoprv935h.execute-api.us-east-2.amazonaws.com/staging/user-settings"
# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  [context.production.environment]
  NODE_VERSION='9.10.0'
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_PROD_ETHEREUM_PROVIDER="https://kovan.infura.io/v3/9c26dd38fd2e44e6bcff6a133eb67930"
  REACT_APP_PROD_ARBITRABLE_TOKEN_LIST_ADDRESS="0xb1323969528dd7cf2e62ff85642c624a8cd5c3fd"
  REACT_APP_PROD_ARBITRABLE_ADDRESS_LIST_ADDRESS="0xcb0216ef49340d63fd22aa16c4ad61658b2875cb"
  REACT_APP_PROD_ARBITRATOR_ADDRESS="0x8847c0947a613c3de443f73351c3815ad0d37f98"
  REACT_APP_PROD_FILE_BASE_URL="https://staging-cfs.s3.us-east-2.amazonaws.com"
  REACT_APP_PROD_FILE_UPLOAD_URL="https://hgyxlve79a.execute-api.us-east-2.amazonaws.com/staging/cfs"
  REACT_APP_PROD_PATCH_USER_SETTINGS_URL="https://hgyxlve79a.execute-api.us-east-2.amazonaws.com/production/user-settings"
