[build]
  publish = "build/"
  command = "yarn build"

  # Develop Branch Deploy context: All deploys that are not in
  # an active Deploy Preview will inherit these settings.
[context.develop]
  [context.develop.environment]
  NODE_VERSION='9.10.0'
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_PROD_ETHEREUM_PROVIDER="https://kovan.infura.io/v3/9c26dd38fd2e44e6bcff6a133eb67930"
  REACT_APP_DEV_ARBITRABLE_TOKEN_LIST_ADDRESS="0x5acb90c7b1822e0b65fba7786db1b7d1266815cb"
  REACT_APP_DEV_ARBITRABLE_ADDRESS_LIST_ADDRESS="0x77fdfc7e33caf96c48f5451e7160665aeed55cf4"
  REACT_APP_DEV_ARBITRATOR_ADDRESS="0x7a5a9d8235a7bd3cd75adc8f1089c51da113b2cc"
  REACT_APP_DEV_FILE_BASE_URL="https://staging-cfs.s3.us-east-2.amazonaws.com"
  REACT_APP_DEV_FILE_UPLOAD_URL="https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/cfs"
# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  [context.production.environment]
  NODE_VERSION='9.10.0'
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_PROD_ETHEREUM_PROVIDER="https://kovan.infura.io/v3/9c26dd38fd2e44e6bcff6a133eb67930"
  REACT_APP_PROD_ARBITRABLE_TOKEN_LIST_ADDRESS="0x5acb90c7b1822e0b65fba7786db1b7d1266815cb"
  REACT_APP_PROD_ARBITRABLE_ADDRESS_LIST_ADDRESS="0x77fdfc7e33caf96c48f5451e7160665aeed55cf4"
  REACT_APP_PROD_ARBITRATOR_ADDRESS="0x7a5a9d8235a7bd3cd75adc8f1089c51da113b2cc"
  REACT_APP_PROD_FILE_BASE_URL="https://staging-cfs.s3.us-east-2.amazonaws.com"
  REACT_APP_PROD_FILE_UPLOAD_URL="https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/cfs"
