[build]
  publish = "build/"
  command = "yarn build"

  # Develop Branch Deploy context: All deploys that are not in
  # an active Deploy Preview will inherit these settings.
[context.develop]
  [context.develop.environment]
  NODE_VERSION='9.10.0'
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_PROD_ETHEREUM_PROVIDER="https://kovan.infura.io/v3/9c26dd38fd2e44e6bcff6a133eb67930"
  REACT_APP_DEV_ARBITRABLE_TOKEN_LIST_ADDRESS="0xc0b34d79c732eee54155182f76856b4eaea7c0f6"
  REACT_APP_DEV_ARBITRABLE_ADDRESS_LIST_ADDRESS="0xdd6e3544eb9ab21d54db7bc8f6b75be8a984925f"
  REACT_APP_DEV_ARBITRATOR_ADDRESS="0xa0ca0d19cab7d2064b620f80a692b275d94f0ed4"
  REACT_APP_DEV_FILE_BASE_URL="https://staging-cfs.s3.us-east-2.amazonaws.com"
  REACT_APP_DEV_FILE_UPLOAD_URL="https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/cfs"
  REACT_APP_DEV_PATCH_USER_SETTINGS_URL="https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/user-settings"
# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  [context.production.environment]
  NODE_VERSION='9.10.0'
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_PROD_ETHEREUM_PROVIDER="https://kovan.infura.io/v3/9c26dd38fd2e44e6bcff6a133eb67930"
  REACT_APP_PROD_ARBITRABLE_TOKEN_LIST_ADDRESS="0xc0b34d79c732eee54155182f76856b4eaea7c0f6"
  REACT_APP_PROD_ARBITRABLE_ADDRESS_LIST_ADDRESS="0xdd6e3544eb9ab21d54db7bc8f6b75be8a984925f"
  REACT_APP_PROD_ARBITRATOR_ADDRESS="0xa0ca0d19cab7d2064b620f80a692b275d94f0ed4"
  REACT_APP_PROD_FILE_BASE_URL="https://staging-cfs.s3.us-east-2.amazonaws.com"
  REACT_APP_PROD_FILE_UPLOAD_URL="https://hgyxlve79a.execute-api.us-east-2.amazonaws.com/staging/cfs"
  REACT_APP_PROD_PATCH_USER_SETTINGS_URL="https://hgyxlve79a.execute-api.us-east-2.amazonaws.com/production/user-settings"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/evidence/t2cr"
  [headers.values]
    Access-Control-Allow-Origin = ["https://kleros-court.netlify.com", "http://localhost", "https://localhost"]